export const api = [
  {
      id: 1,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Desert Safari Adventure",
      tour: 'Experience the thrill of the desert with a thrilling safari ride and breathtaking views.',
      price: 32,
      attri:'Adventure',
  },
  {
      id: 2,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t2.jpg',
      title: "Mountain Trekking Expedition",
      tour: 'Join us for a challenging trek through the stunning mountain ranges.',
      price: 56,
      attri:'Adventure',
  },
  {
      id: 3,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t3.jpg',
      title: "Relaxing Beach Getaway",
      tour: 'Unwind on the beautiful sandy beaches and enjoy the sun and surf.',
      price: 78,
      attri:'Adventure',
  },
  {
      id: 4,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t4.jpg',
      title: "City Exploration Tour",
      tour: 'Explore the vibrant life of the city, its culture and history.',
      price: 98,
      attri:'Adventure',
  },
  {
      id: 5,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t5.jpg',
      title: "Culinary Experience",
      tour: 'Taste the best dishes from local chefs and learn their secrets.',
      price: 122,
      attri:'Family Tours',
  },
  {
      id: 6,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Wildlife Safari",
      tour: 'Get up close with nature and see wildlife in their natural habitat.',
      price: 345 ,
      attri:'Family Tours',
  },
  {
      id: 7,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t5.jpg',
      title: "Cultural Heritage Tour",
      tour: 'Discover the rich heritage and traditions of the local culture.',
      price: 122,
      attri:'Family Tours',
  },
  {
      id: 8,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Adventure Sports Retreat",
      tour: 'Engage in thrilling activities like paragliding and rock climbing.',
      price: 345,
      attri:'Family Tours',
  },
  {
      id: 9,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t5.jpg',
      title: "Historical Sites Tour",
      tour: 'Visit ancient ruins and learn about their historical significance.',
      price: 35,
      attri:'City Cards',
  },
  {
      id: 10,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t3.jpg',
      title: "Luxury Spa Retreat",
      tour: 'Indulge in a relaxing getaway with top-notch spa treatments.',
      price: 326,
      attri:'City Cards',
  },
  {
      id: 11,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t2.jpg',
      title: "Yoga and Wellness Retreat",
      tour: 'Focus on your well-being with yoga sessions and healthy cuisine.',
      price: 232,
      attri:'Family Tours',
  },
  {
      id: 12,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Scenic Train Journey",
      tour: 'Enjoy breathtaking views on a scenic train ride through the countryside.',
      price: 334,
      attri:'City Cards',
  },
  {
      id: 13,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t4.jpg',
      title: "Photography Tour",
      tour: 'Capture stunning landscapes with expert photographers.',
      price: 100,
      attri:'Family Tours',
  },
  {
      id: 14,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t5.jpg',
      title: "Camping Under the Stars",
      tour: 'Spend a night camping under the stars in a serene setting.',
      price: 232,
      attri:'City Cards',
  },
  {
      id: 15,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t3.jpg',
      title: "Cycling Tour",
      tour: 'Explore the scenic routes on a guided cycling adventure.',
      price: 42,
      attri:'City Cards',
  },
  {
      id: 16,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t2.jpg',
      title: "Fishing Expedition",
      tour: 'Join us for a day of fishing and relaxing on the water.',
      price: 3652,
      attri:'City Cards',
  },
  {
      id: 17,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Skydiving Adventure",
      tour: 'Experience the ultimate thrill of free-falling from the sky.',
      price: 732,
      attri:'Multi-Day Trips',
  },
  {
      id: 18,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Sailing Tour",
      tour: 'Enjoy a relaxing day sailing on crystal clear waters.',
      price: 672,
      attri:'Multi-Day Trips',
  },
  {
      id: 19,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Horseback Riding",
      tour: 'Explore beautiful trails on horseback with experienced guides.',
      price: 323,
      attri:'Multi-Day Trips',
  },
  {
      id: 20,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Surfing Lessons",
      tour: 'Catch some waves with our professional surfing instructors.',
      price: 342,
      attri:'Multi-Day Trips',
  },
  {
      id: 21,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Wine Tasting Tour",
      tour: 'Discover local wineries and taste exquisite wines.',
      price: 3256,
      attri:'Adventure',
  },
  {
      id: 22,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Art and Culture Tour",
      tour: 'Immerse yourself in the local art scene and culture.',
      price: 3235,
      attri:'Adventure',
  },
  {
      id: 23,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Gastronomy Tour",
      tour: 'Savor the flavors of the region with a culinary adventure.',
      price: 325,
      attri:'City Cards',
  },
  {
      id: 24,
      images: ['/images/t1.jpg', '/images/t2.jpg', '/images/t3.jpg'],
      img: '/images/t1.jpg',
      title: "Adventure Park Experience",
      tour: 'Enjoy a day full of fun and excitement at the adventure park.',
      price: 3254,
      attri:'City Cards',
  },
];